#!/usr/bin/env bash
#
#    00-header - create the header of the MOTD
#    Copyright (c) 2013 Nick Charlton
#    Copyright (c) 2009-2010 Canonical Ltd.
#
#    Authors: Nick Charlton &amp;amp;amp;lt;hello@nickcharlton.net&amp;amp;amp;gt;
#             Dustin Kirkland &amp;amp;amp;lt;kirkland@canonical.com&amp;amp;amp;gt;
#    Modified by Oitibs: https://oitibs.com/?s=Debian+Dynamic+MOTD
#    Modified by Leitbogioro: https://github.com/leitbogioro/
#                             https://www.zhihu.com/column/originaltechnic
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

DISTRIB_DESCRIPTION="${DISTRIB_DESCRIPTION:-}"

# Prefer /etc/os-release (fast), fallback to lsb_release (slow)
if [[ -z "$DISTRIB_DESCRIPTION" ]] && [[ -r /etc/os-release ]]; then
  # shellcheck disable=SC1091
  . /etc/os-release
  DISTRIB_DESCRIPTION="${PRETTY_NAME:-}"
fi

if [[ -z "$DISTRIB_DESCRIPTION" ]] && command -v lsb_release >/dev/null 2>&1; then
  DISTRIB_DESCRIPTION="$(lsb_release -s -d 2>/dev/null)"
fi

[[ -z "$DISTRIB_DESCRIPTION" ]] && DISTRIB_DESCRIPTION="Debian GNU/Linux"

printf "Welcome to %s (%s)\n" "$DISTRIB_DESCRIPTION" "$(uname -r)"
printf "\n"
printf "The programs included with the Debian GNU/Linux system are free software;\n"
printf "the exact distribution terms for each program are described in the\n"
printf "individual files in /usr/share/doc/*/copyright.\n"
printf "\n"
printf "Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent\n"
printf "permitted by applicable law.\n"
printf "\n"
