#!/usr/bin/env bash
#
#    90-footer - show upgradable packages count (optimized)
#    Authors:Leitbogioro
#    https://github.com/leitbogioro/
#    https://www.zhihu.com/column/originaltechnic
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -o pipefail

have_cmd() { command -v "$1" >/dev/null 2>&1; }

run_timeout() {
  local t="$1"; shift
  if have_cmd timeout; then
    timeout "$t" "$@" 2>/dev/null
  else
    "$@" 2>/dev/null
  fi
}

have_cmd apt || exit 0

UpdateNum="$(
  run_timeout 3s apt list --upgradable 2>/dev/null \
    | awk 'NF{n++} END{print n+0}'
)"

if [[ "$UpdateNum" =~ ^[0-9]+$ ]]; then
  if [[ "$UpdateNum" -eq 1 ]]; then
    printf "%s package can be upgraded. Run 'apt list --upgradable' to see it.\n" "$UpdateNum"
  elif [[ "$UpdateNum" -gt 1 ]]; then
    printf "%s packages can be upgraded. Run 'apt list --upgradable' to see them.\n" "$UpdateNum"
  fi
fi
